name: Deploy Production

on:
  push:
    branches: [production]

jobs:
  name: Deploy Production
  runs-on: ubuntu-latest

  steps:
    - name: Deploy to Production
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
      service-id: ${{ secrets.SERVICE_ID }}
      api-key: ${{ secrets.RENDER_API_KEY }}